import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/SessionProvider";
import ChatBotWrapper from "@/components/ChatBotWrapper";
import { ChatBotProvider } from "@/contexts/ChatBotContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <ChatBotProvider>
            {children}
            <ChatBotWrapper apiKey={process.env.NEXT_PUBLIC_OPENAI_API_KEY || ""} />
          </ChatBotProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
